import {
  Bot, Search, GraduationCap, Palette, Image as ImageIcon, Film, Music, Scissors,
  MessageCircle, FileText, Cloud, FileDown, Code2, ShoppingBag, PlaySquare,
  CreditCard, HeartPulse, Plane,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type Pricing = "Free" | "Paid" | "Freemium" | "Free + Paid";

export type Website = {
  name: string;
  url: string;
  domain: string;
  description: string;
  category: string;
  pricing: Pricing;
  official?: boolean;
  popular?: boolean;
  isNew?: boolean;
  logoUrl?: string;
};

export type Category = {
  id: string;
  name: string;
  icon: LucideIcon;
  emoji: string;
  tint: string; // tailwind bg tint
  iconColor: string;
};

export const categories: Category[] = [
  { id: "ai-chatbots", name: "AI Chatbots", icon: Bot, emoji: "🤖", tint: "bg-blue-50", iconColor: "text-blue-600" },
  { id: "search-engines", name: "Search Engines", icon: Search, emoji: "🔍", tint: "bg-emerald-50", iconColor: "text-emerald-600" },
  { id: "learning", name: "Learning", icon: GraduationCap, emoji: "📚", tint: "bg-violet-50", iconColor: "text-violet-600" },
  { id: "graphic-design", name: "Graphic Design", icon: Palette, emoji: "🎨", tint: "bg-pink-50", iconColor: "text-pink-600" },
  { id: "ai-image", name: "AI Image", icon: ImageIcon, emoji: "🖼️", tint: "bg-amber-50", iconColor: "text-amber-600" },
  { id: "ai-video", name: "AI Video", icon: Film, emoji: "🎥", tint: "bg-rose-50", iconColor: "text-rose-600" },
  { id: "voice-music", name: "Voice & Music", icon: Music, emoji: "🎵", tint: "bg-fuchsia-50", iconColor: "text-fuchsia-600" },
  { id: "video-editing", name: "Video Editing", icon: Scissors, emoji: "📱", tint: "bg-cyan-50", iconColor: "text-cyan-600" },
  { id: "communication", name: "Communication", icon: MessageCircle, emoji: "💬", tint: "bg-sky-50", iconColor: "text-sky-600" },
  { id: "productivity", name: "Productivity", icon: FileText, emoji: "📄", tint: "bg-indigo-50", iconColor: "text-indigo-600" },
  { id: "cloud-storage", name: "Cloud Storage", icon: Cloud, emoji: "☁️", tint: "bg-slate-100", iconColor: "text-slate-600" },
  { id: "pdf-tools", name: "PDF & File Tools", icon: FileDown, emoji: "📂", tint: "bg-red-50", iconColor: "text-red-600" },
  { id: "developers", name: "Developers", icon: Code2, emoji: "💻", tint: "bg-zinc-100", iconColor: "text-zinc-700" },
  { id: "shopping", name: "Shopping", icon: ShoppingBag, emoji: "🛍", tint: "bg-orange-50", iconColor: "text-orange-600" },
  { id: "entertainment", name: "Entertainment", icon: PlaySquare, emoji: "🎬", tint: "bg-red-50", iconColor: "text-red-600" },
  { id: "payments", name: "Payments", icon: CreditCard, emoji: "💳", tint: "bg-green-50", iconColor: "text-green-600" },
  { id: "health", name: "Health", icon: HeartPulse, emoji: "🩺", tint: "bg-rose-50", iconColor: "text-rose-600" },
  { id: "travel", name: "Travel", icon: Plane, emoji: "🌍", tint: "bg-sky-50", iconColor: "text-sky-600" },
];

const w = (
  name: string, url: string, description: string, category: string, pricing: Pricing,
  extras: Partial<Website> = {},
): Website => ({
  name, url, domain: new URL(url).hostname.replace(/^www\./, ""),
  description, category, pricing, official: true, ...extras,
});

export const websites: Website[] = [
  // AI Chatbots
  w("ChatGPT", "https://chat.openai.com", "AI assistant for writing, learning, coding, and more.", "ai-chatbots", "Free + Paid", { popular: true }),
  w("Claude", "https://claude.ai", "AI assistant built by Anthropic to help you do more.", "ai-chatbots", "Free + Paid", { popular: true }),
  w("Gemini", "https://gemini.google.com", "Google's AI assistant for information and ideas.", "ai-chatbots", "Free", { popular: true }),
  w("Perplexity", "https://www.perplexity.ai", "AI-powered search engine for real answers.", "ai-chatbots", "Free + Paid", { popular: true }),
  w("Microsoft Copilot", "https://copilot.microsoft.com", "Your everyday AI companion by Microsoft.", "ai-chatbots", "Free", { popular: true }),
  w("Grok", "https://grok.com", "Conversational AI by xAI.", "ai-chatbots", "Free + Paid"),
  w("Poe", "https://poe.com", "Chat with many AI models in one place.", "ai-chatbots", "Freemium"),
  w("DeepSeek", "https://www.deepseek.com", "Open, powerful AI models and chat.", "ai-chatbots", "Free"),
  w("Meta AI", "https://www.meta.ai", "Meta's conversational AI assistant.", "ai-chatbots", "Free"),
  w("Mistral Le Chat", "https://chat.mistral.ai", "Chat with Mistral's AI models.", "ai-chatbots", "Freemium"),
  w("Character.AI", "https://character.ai", "Conversations with AI characters.", "ai-chatbots", "Freemium"),
  w("Pi", "https://pi.ai", "Personal AI companion for conversation.", "ai-chatbots", "Free"),
  w("HuggingChat", "https://huggingface.co/chat", "Chat with open AI models.", "ai-chatbots", "Free"),
  w("You.com", "https://you.com", "AI answers, research and chat.", "ai-chatbots", "Freemium"),
  w("Phind", "https://www.phind.com", "AI answers for technical questions.", "ai-chatbots", "Freemium"),
  w("Qwen Chat", "https://chat.qwen.ai", "Alibaba's multilingual AI assistant.", "ai-chatbots", "Free"),
  w("Kimi", "https://www.kimi.com", "AI assistant for research and writing.", "ai-chatbots", "Freemium"),
  w("Duck.ai", "https://duck.ai", "Private chats with AI models.", "ai-chatbots", "Free"),
  w("Jasper", "https://www.jasper.ai", "AI assistant for marketing teams.", "ai-chatbots", "Paid"),
  w("Copy.ai", "https://www.copy.ai", "AI workspace for marketing and sales.", "ai-chatbots", "Freemium"),

  // Search
  w("Google", "https://www.google.com", "The world's most popular search engine.", "search-engines", "Free", { popular: true }),
  w("Bing", "https://www.bing.com", "Microsoft's search engine with AI features.", "search-engines", "Free"),
  w("DuckDuckGo", "https://duckduckgo.com", "Privacy-focused search engine.", "search-engines", "Free"),
  w("Yahoo Search", "https://search.yahoo.com", "Yahoo's classic web search.", "search-engines", "Free"),
  w("Brave Search", "https://search.brave.com", "Independent, private search.", "search-engines", "Free"),
  w("Startpage", "https://www.startpage.com", "Private Google search results.", "search-engines", "Free"),
  w("Ecosia", "https://www.ecosia.org", "The search engine that plants trees.", "search-engines", "Free"),
  w("Qwant", "https://www.qwant.com", "European private search engine.", "search-engines", "Free"),
  w("Kagi", "https://kagi.com", "Ad-free search with personalized results.", "search-engines", "Paid"),
  w("Mojeek", "https://www.mojeek.com", "Independent search with its own index.", "search-engines", "Free"),
  w("Swisscows", "https://swisscows.com", "Privacy-friendly web search.", "search-engines", "Free"),
  w("Yep", "https://yep.com", "Independent search from Ahrefs.", "search-engines", "Free"),
  w("Yandex", "https://yandex.com", "Web search and online services.", "search-engines", "Free"),
  w("Naver", "https://www.naver.com", "Korean web search portal.", "search-engines", "Free"),
  w("WolframAlpha", "https://www.wolframalpha.com", "Computational answers and knowledge.", "search-engines", "Freemium"),
  w("Internet Archive", "https://archive.org", "Search preserved web pages and media.", "search-engines", "Free"),
  w("Marginalia Search", "https://search.marginalia.nu", "Discover independent, non-commercial sites.", "search-engines", "Free"),
  w("SearXNG", "https://searx.space", "Find public instances of open metasearch.", "search-engines", "Free"),

  // Learning
  w("Khan Academy", "https://www.khanacademy.org", "Free world-class education for anyone.", "learning", "Free"),
  w("Coursera", "https://www.coursera.org", "Online courses from top universities.", "learning", "Freemium"),
  w("Udemy", "https://www.udemy.com", "Learn anything, anytime, anywhere.", "learning", "Paid"),
  w("freeCodeCamp", "https://www.freecodecamp.org", "Learn to code for free.", "learning", "Free"),
  w("Duolingo", "https://www.duolingo.com", "Learn languages for free.", "learning", "Freemium"),
  w("edX", "https://www.edx.org", "Online courses from Harvard, MIT, and more.", "learning", "Freemium"),
  w("Skillshare", "https://www.skillshare.com", "Online classes for creators.", "learning", "Paid"),
  w("Codecademy", "https://www.codecademy.com", "Learn to code interactively.", "learning", "Freemium"),
  w("MIT OpenCourseWare", "https://ocw.mit.edu", "Free MIT course materials.", "learning", "Free"),
  w("Harvard Online", "https://pll.harvard.edu", "Online courses from Harvard.", "learning", "Free + Paid"),
  w("FutureLearn", "https://www.futurelearn.com", "Online courses from universities.", "learning", "Freemium"),
  w("Brilliant", "https://brilliant.org", "Interactive math and science lessons.", "learning", "Freemium"),
  w("OpenLearn", "https://www.open.edu/openlearn", "Free courses from The Open University.", "learning", "Free"),
  w("Alison", "https://alison.com", "Free online certificate courses.", "learning", "Freemium"),
  w("Udacity", "https://www.udacity.com", "Technology and career courses.", "learning", "Paid"),
  w("The Odin Project", "https://www.theodinproject.com", "Free full-stack web development curriculum.", "learning", "Free"),
  w("W3Schools", "https://www.w3schools.com", "Web development tutorials and references.", "learning", "Free"),
  w("Saylor Academy", "https://www.saylor.org", "Free self-paced college-level courses.", "learning", "Free"),

  // Graphic Design
  w("Canva", "https://www.canva.com", "Design anything and publish anywhere.", "graphic-design", "Freemium", { popular: true }),
  w("Figma", "https://www.figma.com", "Collaborative interface design tool.", "graphic-design", "Freemium"),
  w("Adobe Express", "https://www.adobe.com/express", "Quick and easy content creation.", "graphic-design", "Freemium"),
  w("Photopea", "https://www.photopea.com", "Free online photo editor.", "graphic-design", "Free"),
  w("Pixlr", "https://pixlr.com", "AI-powered photo editing.", "graphic-design", "Freemium"),
  w("VistaCreate", "https://create.vista.com", "Easy graphic design and video maker.", "graphic-design", "Freemium"),
  w("Affinity Designer", "https://affinity.serif.com/designer", "Professional vector design software.", "graphic-design", "Paid"),
  w("CorelDRAW", "https://www.coreldraw.com", "Professional graphic design suite.", "graphic-design", "Paid"),
  w("Penpot", "https://penpot.app", "Open-source design and prototyping.", "graphic-design", "Free"),
  w("Sketch", "https://www.sketch.com", "Digital product design on Mac.", "graphic-design", "Paid"),
  w("Framer", "https://www.framer.com", "Design and publish interactive websites.", "graphic-design", "Freemium"),
  w("Vectr", "https://vectr.com", "Online vector graphics editor.", "graphic-design", "Freemium"),
  w("Lunacy", "https://icons8.com/lunacy", "Free graphic design software.", "graphic-design", "Free"),
  w("Inkscape", "https://inkscape.org", "Open-source vector graphics editor.", "graphic-design", "Free"),
  w("GIMP", "https://www.gimp.org", "Open-source image editing software.", "graphic-design", "Free"),
  w("Krita", "https://krita.org", "Free digital painting software.", "graphic-design", "Free"),
  w("Coolors", "https://coolors.co", "Create and explore color palettes.", "graphic-design", "Freemium"),
  w("Remove.bg", "https://www.remove.bg", "Remove image backgrounds automatically.", "graphic-design", "Freemium"),

  // AI Image
  w("Midjourney", "https://www.midjourney.com", "AI image generation.", "ai-image", "Paid"),
  w("Leonardo AI", "https://leonardo.ai", "Creative AI image platform.", "ai-image", "Freemium"),
  w("Ideogram", "https://ideogram.ai", "AI images with legible text.", "ai-image", "Freemium"),
  w("Adobe Firefly", "https://firefly.adobe.com", "Adobe's generative AI.", "ai-image", "Freemium"),
  w("Recraft", "https://www.recraft.ai", "AI for designers.", "ai-image", "Freemium"),
  w("Playground AI", "https://playground.com", "Free AI image creation.", "ai-image", "Freemium"),
  w("Krea AI", "https://www.krea.ai", "Real-time AI image generation.", "ai-image", "Freemium"),
  w("Stable Diffusion", "https://stability.ai", "Open-source AI image generation.", "ai-image", "Free + Paid"),
  w("DALL·E", "https://openai.com/index/dall-e-3", "OpenAI's image generation model.", "ai-image", "Free + Paid"),
  w("Microsoft Designer", "https://designer.microsoft.com", "Create images and designs with AI.", "ai-image", "Freemium"),
  w("DreamStudio", "https://dreamstudio.ai", "Generate images with Stability AI.", "ai-image", "Paid"),
  w("NightCafe", "https://creator.nightcafe.studio", "Create and share AI art.", "ai-image", "Freemium"),
  w("Artbreeder", "https://www.artbreeder.com", "Create and remix AI images.", "ai-image", "Freemium"),
  w("getimg.ai", "https://getimg.ai", "Generate and edit images with AI.", "ai-image", "Freemium"),
  w("Civitai", "https://civitai.com", "Explore AI image models and creations.", "ai-image", "Freemium"),
  w("OpenArt", "https://openart.ai", "AI image generation and editing.", "ai-image", "Freemium"),
  w("Tensor.Art", "https://tensor.art", "Create art with community AI models.", "ai-image", "Freemium"),
  w("Freepik AI", "https://www.freepik.com/ai", "Generate design assets with AI.", "ai-image", "Freemium"),

  // AI Video
  w("Runway", "https://runwayml.com", "AI video generation and editing.", "ai-video", "Freemium"),
  w("Kling AI", "https://kling.kuaishou.com", "AI video from text and images.", "ai-video", "Freemium"),
  w("Pika", "https://pika.art", "Idea-to-video AI platform.", "ai-video", "Freemium"),
  w("PixVerse", "https://pixverse.ai", "AI video creation for everyone.", "ai-video", "Freemium"),
  w("Luma AI", "https://lumalabs.ai", "Dream machine for AI video.", "ai-video", "Freemium"),
  w("Hailuo AI", "https://hailuoai.video", "AI video generation by MiniMax.", "ai-video", "Freemium"),
  w("InVideo AI", "https://invideo.io/ai", "AI-powered video creation.", "ai-video", "Freemium"),
  w("Synthesia", "https://www.synthesia.io", "AI video generation with avatars.", "ai-video", "Paid"),
  w("Google Flow", "https://labs.google/fx/tools/flow", "AI filmmaking with Google's video models.", "ai-video", "Free + Paid"),
  w("Sora", "https://sora.com", "Create videos with OpenAI.", "ai-video", "Free + Paid"),
  w("HeyGen", "https://www.heygen.com", "AI avatars and video translation.", "ai-video", "Freemium"),
  w("Colossyan", "https://www.colossyan.com", "Training videos with AI presenters.", "ai-video", "Paid"),
  w("D-ID", "https://www.d-id.com", "Talking avatar videos from images.", "ai-video", "Freemium"),
  w("Vidu", "https://www.vidu.com", "Generate video from text and images.", "ai-video", "Freemium"),
  w("Higgsfield", "https://higgsfield.ai", "AI video creation and effects.", "ai-video", "Freemium"),
  w("Kaiber", "https://kaiber.ai", "AI visuals and music videos.", "ai-video", "Paid"),
  w("VEED AI", "https://www.veed.io/tools/ai-video", "Create videos with AI tools.", "ai-video", "Freemium"),
  w("Steve AI", "https://www.steve.ai", "Turn scripts into animated videos.", "ai-video", "Freemium"),

  // Voice & Music
  w("ElevenLabs", "https://elevenlabs.io", "Realistic AI voice generation.", "voice-music", "Freemium"),
  w("Murf AI", "https://murf.ai", "AI voiceovers in minutes.", "voice-music", "Freemium"),
  w("PlayHT", "https://play.ht", "AI voice generator and text to speech.", "voice-music", "Freemium"),
  w("Suno", "https://suno.com", "Create original songs with AI.", "voice-music", "Freemium"),
  w("Udio", "https://www.udio.com", "AI music creation platform.", "voice-music", "Freemium"),
  w("AIVA", "https://www.aiva.ai", "AI music composition.", "voice-music", "Freemium"),
  w("Soundraw", "https://soundraw.io", "AI music generator for creators.", "voice-music", "Freemium"),
  w("Voicemod", "https://www.voicemod.net", "Real-time voice changer and soundboard.", "voice-music", "Freemium"),
  w("Resemble AI", "https://www.resemble.ai", "AI voice cloning and speech generation.", "voice-music", "Paid"),
  w("Speechify", "https://speechify.com", "Listen to text with natural voices.", "voice-music", "Freemium"),
  w("LOVO", "https://lovo.ai", "AI voiceovers and text to speech.", "voice-music", "Freemium"),
  w("WellSaid", "https://wellsaidlabs.com", "Studio-quality AI voiceovers.", "voice-music", "Paid"),
  w("Kits AI", "https://www.kits.ai", "AI vocals and music production.", "voice-music", "Freemium"),
  w("Beatoven.ai", "https://www.beatoven.ai", "Royalty-free AI background music.", "voice-music", "Freemium"),
  w("Boomy", "https://boomy.com", "Create songs with AI.", "voice-music", "Freemium"),
  w("Loudly", "https://www.loudly.com", "AI music generation for creators.", "voice-music", "Freemium"),
  w("Soundful", "https://soundful.com", "AI-generated music tracks.", "voice-music", "Freemium"),
  w("Adobe Podcast", "https://podcast.adobe.com", "AI audio recording and enhancement.", "voice-music", "Freemium"),

  // Video Editing
  w("CapCut", "https://www.capcut.com", "All-in-one video editor.", "video-editing", "Freemium"),
  w("VN Editor", "https://www.vlognow.me", "Free professional video editor.", "video-editing", "Free"),
  w("DaVinci Resolve", "https://www.blackmagicdesign.com/products/davinciresolve", "Pro video editing and color.", "video-editing", "Free + Paid"),
  w("Clipchamp", "https://clipchamp.com", "Easy online video editor.", "video-editing", "Freemium"),
  w("Descript", "https://www.descript.com", "Edit video like a doc.", "video-editing", "Freemium"),
  w("Filmora", "https://filmora.wondershare.com", "Easy and powerful video editor.", "video-editing", "Freemium"),
  w("Adobe Premiere Pro", "https://www.adobe.com/products/premiere.html", "Industry-standard video editing.", "video-editing", "Paid"),
  w("Final Cut Pro", "https://www.apple.com/final-cut-pro", "Professional video editing for Mac.", "video-editing", "Paid"),
  w("VEED", "https://www.veed.io", "Online video editor and subtitles.", "video-editing", "Freemium"),
  w("Kapwing", "https://www.kapwing.com", "Collaborative online video editing.", "video-editing", "Freemium"),
  w("Kdenlive", "https://kdenlive.org", "Open-source video editor.", "video-editing", "Free"),
  w("Shotcut", "https://shotcut.org", "Free cross-platform video editing.", "video-editing", "Free"),
  w("OpenShot", "https://www.openshot.org", "Easy open-source video editor.", "video-editing", "Free"),
  w("iMovie", "https://www.apple.com/imovie", "Free video editing on Apple devices.", "video-editing", "Free"),
  w("Lightworks", "https://lwks.com", "Professional video editing software.", "video-editing", "Free + Paid"),
  w("Movavi", "https://www.movavi.com", "Simple video editing tools.", "video-editing", "Paid"),
  w("Camtasia", "https://www.techsmith.com/camtasia", "Screen recording and video editing.", "video-editing", "Paid"),
  w("Vimeo Create", "https://vimeo.com/create", "Make and edit videos online.", "video-editing", "Paid"),

  // Communication
  w("WhatsApp", "https://www.whatsapp.com", "Simple, secure messaging.", "communication", "Free"),
  w("Telegram", "https://telegram.org", "Fast and secure messaging.", "communication", "Free"),
  w("Discord", "https://discord.com", "Voice, video, and text chat.", "communication", "Freemium"),
  w("Zoom", "https://zoom.us", "Video meetings and webinars.", "communication", "Freemium"),
  w("Google Meet", "https://meet.google.com", "Secure video meetings.", "communication", "Free"),
  w("Slack", "https://slack.com", "Where work happens — team messaging.", "communication", "Freemium"),
  w("Microsoft Teams", "https://www.microsoft.com/microsoft-teams", "Chat, meet, and collaborate.", "communication", "Freemium"),
  w("Signal", "https://signal.org", "Private, encrypted messaging.", "communication", "Free"),
  w("Google Chat", "https://chat.google.com", "Messaging for teams in Google Workspace.", "communication", "Free + Paid"),
  w("Messenger", "https://www.messenger.com", "Messages and calls from Meta.", "communication", "Free"),
  w("Viber", "https://www.viber.com", "Free messages and calls.", "communication", "Free"),
  w("LINE", "https://line.me", "Messaging, calls and communities.", "communication", "Free"),
  w("WeChat", "https://www.wechat.com", "Messaging and social communication.", "communication", "Free"),
  w("Element", "https://element.io", "Secure messaging on the Matrix network.", "communication", "Freemium"),
  w("Jitsi Meet", "https://meet.jit.si", "Free video conferencing in your browser.", "communication", "Free"),
  w("Cisco Webex", "https://www.webex.com", "Meetings, calling and collaboration.", "communication", "Freemium"),
  w("Mattermost", "https://mattermost.com", "Team collaboration and messaging.", "communication", "Free + Paid"),
  w("Zulip", "https://zulip.com", "Organized team chat with topics.", "communication", "Freemium"),

  // Productivity
  w("Notion", "https://www.notion.so", "All-in-one workspace for notes, tasks, and more.", "productivity", "Freemium", { popular: true }),
  w("Google Docs", "https://docs.google.com", "Online docs, collaborate anywhere.", "productivity", "Free"),
  w("Google Sheets", "https://sheets.google.com", "Online spreadsheets.", "productivity", "Free"),
  w("ClickUp", "https://clickup.com", "One app to replace them all.", "productivity", "Freemium"),
  w("Trello", "https://trello.com", "Boards, lists, and cards.", "productivity", "Freemium"),
  w("Microsoft 365", "https://www.microsoft.com/microsoft-365", "Word, Excel, PowerPoint, and more.", "productivity", "Paid"),
  w("Airtable", "https://www.airtable.com", "Part spreadsheet, part database.", "productivity", "Freemium"),
  w("Asana", "https://asana.com", "Work management for teams.", "productivity", "Freemium"),
  w("Todoist", "https://todoist.com", "Organize tasks and projects.", "productivity", "Freemium"),
  w("Obsidian", "https://obsidian.md", "Connected notes and personal knowledge.", "productivity", "Free + Paid"),
  w("Evernote", "https://evernote.com", "Notes, tasks and documents together.", "productivity", "Freemium"),
  w("Monday.com", "https://monday.com", "Visual work management platform.", "productivity", "Freemium"),
  w("Linear", "https://linear.app", "Product and issue tracking for teams.", "productivity", "Freemium"),
  w("Basecamp", "https://basecamp.com", "Projects, tasks and team communication.", "productivity", "Paid"),
  w("Coda", "https://coda.io", "Docs that combine data and workflows.", "productivity", "Freemium"),
  w("Miro", "https://miro.com", "Collaborative online whiteboard.", "productivity", "Freemium"),
  w("Google Calendar", "https://calendar.google.com", "Plan meetings and manage your schedule.", "productivity", "Free"),
  w("TickTick", "https://ticktick.com", "To-dos, habits and calendars.", "productivity", "Freemium"),

  // Cloud Storage
  w("Google Drive", "https://drive.google.com", "Cloud storage by Google.", "cloud-storage", "Freemium"),
  w("Dropbox", "https://www.dropbox.com", "Files anywhere, always in sync.", "cloud-storage", "Freemium"),
  w("OneDrive", "https://onedrive.live.com", "Microsoft's cloud storage.", "cloud-storage", "Freemium"),
  w("MEGA", "https://mega.io", "Secure cloud storage.", "cloud-storage", "Freemium"),
  w("Box", "https://www.box.com", "Cloud content management.", "cloud-storage", "Freemium"),
  w("iCloud", "https://www.icloud.com", "Apple's cloud storage and sync.", "cloud-storage", "Freemium"),
  w("Sync.com", "https://www.sync.com", "Secure cloud storage with encryption.", "cloud-storage", "Freemium"),
  w("pCloud", "https://www.pcloud.com", "Lifetime cloud storage plans.", "cloud-storage", "Freemium"),
  w("Proton Drive", "https://proton.me/drive", "Encrypted cloud file storage.", "cloud-storage", "Freemium"),
  w("Internxt", "https://internxt.com", "Privacy-first cloud storage.", "cloud-storage", "Freemium"),
  w("Tresorit", "https://tresorit.com", "End-to-end encrypted file storage.", "cloud-storage", "Paid"),
  w("IDrive", "https://www.idrive.com", "Cloud backup and file sync.", "cloud-storage", "Free + Paid"),
  w("Backblaze", "https://www.backblaze.com", "Online backup and cloud storage.", "cloud-storage", "Paid"),
  w("Nextcloud", "https://nextcloud.com", "Self-hosted file sharing and sync.", "cloud-storage", "Free + Paid"),
  w("Koofr", "https://koofr.eu", "Cloud storage and file management.", "cloud-storage", "Freemium"),
  w("MediaFire", "https://www.mediafire.com", "File hosting and sharing.", "cloud-storage", "Freemium"),
  w("Jottacloud", "https://www.jottacloud.com", "Cloud backup and storage.", "cloud-storage", "Paid"),
  w("Filen", "https://filen.io", "Encrypted cloud storage and sync.", "cloud-storage", "Freemium"),

  // PDF
  w("iLovePDF", "https://www.ilovepdf.com", "Every tool you need for PDFs.", "pdf-tools", "Freemium"),
  w("Smallpdf", "https://smallpdf.com", "The platform to work with PDFs.", "pdf-tools", "Freemium"),
  w("PDF24", "https://tools.pdf24.org", "Free PDF tools online.", "pdf-tools", "Free"),
  w("CloudConvert", "https://cloudconvert.com", "Convert anything to anything.", "pdf-tools", "Freemium"),
  w("TinyPNG", "https://tinypng.com", "Smart PNG and JPEG compression.", "pdf-tools", "Free"),
  w("Sejda PDF", "https://www.sejda.com", "Online PDF editor and tools.", "pdf-tools", "Freemium"),
  w("PDF Candy", "https://pdfcandy.com", "Free PDF tools online.", "pdf-tools", "Freemium"),
  w("Convertio", "https://convertio.co", "Convert files between 300+ formats.", "pdf-tools", "Freemium"),
  w("Adobe Acrobat Online", "https://www.adobe.com/acrobat/online.html", "Online PDF editing and conversion.", "pdf-tools", "Freemium"),
  w("PDFgear", "https://www.pdfgear.com", "Free PDF reader and editor.", "pdf-tools", "Free"),
  w("DocHub", "https://www.dochub.com", "Edit and sign PDF documents.", "pdf-tools", "Freemium"),
  w("PDFescape", "https://www.pdfescape.com", "Online PDF editing and forms.", "pdf-tools", "Freemium"),
  w("Soda PDF", "https://www.sodapdf.com", "PDF editing and conversion tools.", "pdf-tools", "Freemium"),
  w("Zamzar", "https://www.zamzar.com", "Convert files online.", "pdf-tools", "Freemium"),
  w("Online-Convert", "https://www.online-convert.com", "Convert documents and media files.", "pdf-tools", "Freemium"),
  w("FreeConvert", "https://www.freeconvert.com", "Convert and compress files online.", "pdf-tools", "Freemium"),
  w("PDF2Go", "https://www.pdf2go.com", "Edit and convert PDFs online.", "pdf-tools", "Freemium"),
  w("Xodo", "https://xodo.com", "Read, edit and sign PDF files.", "pdf-tools", "Freemium"),

  // Developers
  w("GitHub", "https://github.com", "Platform for developers to build and ship software.", "developers", "Free", { popular: true }),
  w("GitLab", "https://gitlab.com", "The DevSecOps platform.", "developers", "Freemium"),
  w("Vercel", "https://vercel.com", "Frontend cloud for developers.", "developers", "Freemium"),
  w("Netlify", "https://www.netlify.com", "Build, deploy, scale modern web apps.", "developers", "Freemium"),
  w("Firebase", "https://firebase.google.com", "Google's app development platform.", "developers", "Freemium"),
  w("CodePen", "https://codepen.io", "Front-end code playground.", "developers", "Freemium"),
  w("StackBlitz", "https://stackblitz.com", "Instant dev environments in the browser.", "developers", "Freemium"),
  w("Replit", "https://replit.com", "Code, collaborate, and deploy online.", "developers", "Freemium"),
  w("Stack Overflow", "https://stackoverflow.com", "Questions and answers for developers.", "developers", "Free"),
  w("MDN Web Docs", "https://developer.mozilla.org", "Documentation for web technologies.", "developers", "Free"),
  w("npm", "https://www.npmjs.com", "JavaScript package registry.", "developers", "Free"),
  w("Docker Hub", "https://hub.docker.com", "Find and share container images.", "developers", "Freemium"),
  w("Cloudflare", "https://www.cloudflare.com", "Web security, performance and developer tools.", "developers", "Free + Paid"),
  w("Render", "https://render.com", "Deploy apps and services.", "developers", "Freemium"),
  w("Railway", "https://railway.com", "Deploy applications and databases.", "developers", "Freemium"),
  w("Supabase", "https://supabase.com", "Open-source app development platform.", "developers", "Freemium"),
  w("Postman", "https://www.postman.com", "Build and test APIs.", "developers", "Freemium"),
  w("CodeSandbox", "https://codesandbox.io", "Cloud development environments.", "developers", "Freemium"),

  // Shopping
  w("Amazon", "https://www.amazon.com", "Everything store.", "shopping", "Free"),
  w("Flipkart", "https://www.flipkart.com", "India's leading online store.", "shopping", "Free"),
  w("Myntra", "https://www.myntra.com", "Fashion and lifestyle shopping.", "shopping", "Free"),
  w("Meesho", "https://www.meesho.com", "Affordable online shopping.", "shopping", "Free"),
  w("eBay", "https://www.ebay.com", "Buy and sell online.", "shopping", "Free"),
  w("Walmart", "https://www.walmart.com", "Save money. Live better.", "shopping", "Free"),
  w("AliExpress", "https://www.aliexpress.com", "Global online marketplace.", "shopping", "Free"),
  w("Etsy", "https://www.etsy.com", "Unique handmade and vintage items.", "shopping", "Free"),
  w("Amazon India", "https://www.amazon.in", "Shop online across India.", "shopping", "Free"),
  w("AJIO", "https://www.ajio.com", "Fashion and lifestyle shopping in India.", "shopping", "Free"),
  w("Nykaa", "https://www.nykaa.com", "Beauty and wellness shopping.", "shopping", "Free"),
  w("Tata CLiQ", "https://www.tatacliq.com", "Fashion, electronics and lifestyle.", "shopping", "Free"),
  w("Croma", "https://www.croma.com", "Electronics and appliances.", "shopping", "Free"),
  w("Best Buy", "https://www.bestbuy.com", "Consumer electronics shopping.", "shopping", "Free"),
  w("Target", "https://www.target.com", "Everyday essentials and more.", "shopping", "Free"),
  w("Temu", "https://www.temu.com", "Global online marketplace.", "shopping", "Free"),
  w("IKEA", "https://www.ikea.com", "Furniture and home accessories.", "shopping", "Free"),
  w("Zara", "https://www.zara.com", "Fashion and accessories online.", "shopping", "Free"),

  // Entertainment
  w("YouTube", "https://www.youtube.com", "Watch, learn, and explore millions of videos.", "entertainment", "Free", { popular: true }),
  w("Netflix", "https://www.netflix.com", "Stream movies and TV shows.", "entertainment", "Paid"),
  w("Prime Video", "https://www.primevideo.com", "Amazon Prime streaming.", "entertainment", "Paid"),
  w("Spotify", "https://www.spotify.com", "Music for everyone.", "entertainment", "Freemium"),
  w("Disney+", "https://www.disneyplus.com", "Movies, shows, and originals.", "entertainment", "Paid"),
  w("Hulu", "https://www.hulu.com", "Stream TV and movies.", "entertainment", "Paid"),
  w("Apple TV+", "https://tv.apple.com", "Apple originals and more.", "entertainment", "Paid"),
  w("Crunchyroll", "https://www.crunchyroll.com", "Anime streaming service.", "entertainment", "Freemium"),
  w("Twitch", "https://www.twitch.tv", "Live streams and gaming communities.", "entertainment", "Free"),
  w("JioHotstar", "https://www.jiohotstar.com", "Movies, sports and series in India.", "entertainment", "Free + Paid"),
  w("ZEE5", "https://www.zee5.com", "Indian movies, shows and originals.", "entertainment", "Free + Paid"),
  w("Sony LIV", "https://www.sonyliv.com", "Sports, shows and films.", "entertainment", "Free + Paid"),
  w("JioSaavn", "https://www.jiosaavn.com", "Stream Indian music and podcasts.", "entertainment", "Freemium"),
  w("SoundCloud", "https://soundcloud.com", "Discover music and creators.", "entertainment", "Freemium"),
  w("Apple Music", "https://music.apple.com", "Stream music and playlists.", "entertainment", "Paid"),
  w("YouTube Music", "https://music.youtube.com", "Music and live performances.", "entertainment", "Free + Paid"),
  w("MUBI", "https://mubi.com", "Curated cinema streaming.", "entertainment", "Paid"),
  w("Plex", "https://www.plex.tv", "Stream movies, TV and your media.", "entertainment", "Freemium"),

  // Payments
  w("Google Pay", "https://pay.google.com", "Fast, simple, secure payments.", "payments", "Free"),
  w("PhonePe", "https://www.phonepe.com", "India's payments app.", "payments", "Free"),
  w("Paytm", "https://paytm.com", "Payments and financial services.", "payments", "Free"),
  w("PayPal", "https://www.paypal.com", "Global online payments.", "payments", "Free"),
  w("Stripe", "https://stripe.com", "Payments infrastructure for the internet.", "payments", "Freemium"),
  w("Wise", "https://wise.com", "International money transfers.", "payments", "Free + Paid"),
  w("Skrill", "https://www.skrill.com", "Digital wallet and payments.", "payments", "Free + Paid"),
  w("Razorpay", "https://razorpay.com", "Payments and business banking for India.", "payments", "Freemium"),
  w("Cash App", "https://cash.app", "Send and receive money.", "payments", "Free"),
  w("Venmo", "https://venmo.com", "Social payments and transfers.", "payments", "Free"),
  w("Zelle", "https://www.zellepay.com", "Send money through your bank.", "payments", "Free"),
  w("Apple Pay", "https://www.apple.com/apple-pay", "Pay with Apple devices.", "payments", "Free"),
  w("Samsung Wallet", "https://www.samsung.com/us/apps/samsung-wallet", "Payments and passes on Samsung devices.", "payments", "Free"),
  w("Payoneer", "https://www.payoneer.com", "Global payments for businesses.", "payments", "Free + Paid"),
  w("Remitly", "https://www.remitly.com", "International money transfers.", "payments", "Free + Paid"),
  w("Western Union", "https://www.westernunion.com", "Send money worldwide.", "payments", "Free + Paid"),
  w("BharatPe", "https://bharatpe.com", "Payments for Indian businesses.", "payments", "Free"),
  w("CRED", "https://cred.club", "Credit card payments and rewards.", "payments", "Free"),

  // Health
  w("Practo", "https://www.practo.com", "Consult doctors online.", "health", "Freemium"),
  w("Apollo 24/7", "https://www.apollo247.com", "Healthcare at your doorstep.", "health", "Freemium"),
  w("WebMD", "https://www.webmd.com", "Better information. Better health.", "health", "Free"),
  w("Mayo Clinic", "https://www.mayoclinic.org", "Trusted medical information.", "health", "Free"),
  w("Healthline", "https://www.healthline.com", "Medical information you can trust.", "health", "Free"),
  w("MedlinePlus", "https://medlineplus.gov", "Trusted health information from the NIH.", "health", "Free"),
  w("Cleveland Clinic", "https://my.clevelandclinic.org", "Health information from Cleveland Clinic.", "health", "Free"),
  w("NHS", "https://www.nhs.uk", "UK's National Health Service.", "health", "Free"),
  w("WHO", "https://www.who.int", "Global public health information.", "health", "Free"),
  w("CDC", "https://www.cdc.gov", "Public health guidance and data.", "health", "Free"),
  w("NIH", "https://www.nih.gov", "Health research and information.", "health", "Free"),
  w("1mg", "https://www.1mg.com", "Medicines and healthcare in India.", "health", "Free"),
  w("PharmEasy", "https://pharmeasy.in", "Order medicines and health tests.", "health", "Free"),
  w("GoodRx", "https://www.goodrx.com", "Compare prescription prices.", "health", "Free"),
  w("Ada Health", "https://ada.com", "Digital symptom assessment.", "health", "Free"),
  w("Verywell Health", "https://www.verywellhealth.com", "Accessible health information.", "health", "Free"),
  w("Zocdoc", "https://www.zocdoc.com", "Find and book healthcare providers.", "health", "Free"),
  w("MyFitnessPal", "https://www.myfitnesspal.com", "Track food and fitness goals.", "health", "Freemium"),

  // Travel
  w("Google Maps", "https://maps.google.com", "Explore the world.", "travel", "Free"),
  w("Booking.com", "https://www.booking.com", "Book hotels worldwide.", "travel", "Free"),
  w("Airbnb", "https://www.airbnb.com", "Stays and experiences.", "travel", "Free"),
  w("Uber", "https://www.uber.com", "Ride, eat, and more.", "travel", "Free"),
  w("MakeMyTrip", "https://www.makemytrip.com", "Flights, hotels, and holidays.", "travel", "Free"),
  w("Expedia", "https://www.expedia.com", "Flights, hotels, cars, and packages.", "travel", "Free"),
  w("Agoda", "https://www.agoda.com", "Book hotels and flights worldwide.", "travel", "Free"),
  w("Skyscanner", "https://www.skyscanner.com", "Compare cheap flights, hotels, cars.", "travel", "Free"),
  w("Tripadvisor", "https://www.tripadvisor.com", "Travel reviews and trip planning.", "travel", "Free"),
  w("Google Flights", "https://www.google.com/travel/flights", "Search and compare flights.", "travel", "Free"),
  w("Kayak", "https://www.kayak.com", "Search flights, hotels and cars.", "travel", "Free"),
  w("Trip.com", "https://www.trip.com", "Book flights, hotels and trains.", "travel", "Free"),
  w("Hostelworld", "https://www.hostelworld.com", "Find hostels around the world.", "travel", "Free"),
  w("Rome2Rio", "https://www.rome2rio.com", "Compare routes across transport types.", "travel", "Free"),
  w("IRCTC", "https://www.irctc.co.in", "Book Indian Railways tickets.", "travel", "Free"),
  w("ixigo", "https://www.ixigo.com", "Book trains, flights and buses in India.", "travel", "Free"),
  w("OYO", "https://www.oyorooms.com", "Find and book stays.", "travel", "Free"),
  w("Lonely Planet", "https://www.lonelyplanet.com", "Travel guides and destination ideas.", "travel", "Free"),
];

export function categoryById(id: string) {
  return categories.find((c) => c.id === id);
}

export function faviconFor(domain: string) {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
}